name: Release GUI Tweaks

on:
  push:
#    branches:
#      - main
#    paths:
#      - 'GUI Tweaks/**'
    tags:
      - '*'

jobs:
  tagged-release:
    name: "Release GUI Tweaks"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: GetVersion
        id: getversion
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Zip "GUI Tweaks"
        run: |
          NEWDIR="Ejsstiil's GUI Tweaks ${{ steps.getversion.outputs.version }}"
          mv "GUI Tweaks" "$NEWDIR"
          cp ./LICENSE "$NEWDIR"/
          cp ./README.md "$NEWDIR"/
          zip -r "GUI-Tweaks-${{ steps.getversion.outputs.version }}.zip" "$NEWDIR"/

      - name: "Create a Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip


