name: Manual Release GUI Tweaks

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'GUI Tweaks/**'
#    tags:
#      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string
        default: 'v1.'


jobs:
  release_new_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          #ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: GetVersion
        id: getversion
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Zip "GUI Tweaks"
        run: |
          NEWDIR="Ejsstiil's GUI Tweaks ${{ steps.getversion.outputs.version }}"
          mv "GUI Tweaks" "$NEWDIR"
          cp ./LICENSE "$NEWDIR"/
          cp ./README.md "$NEWDIR"/
          ls -lar
          cd "$NEWDIR"
          ls -lar
          
          
